version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=CharLemAznable_vertx-diamond-config

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
